package  br.com.fatec.les.selenium;
//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RelatorioTest {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
 driver = new FirefoxDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void relatorio() throws InterruptedException {
 driver.get("http://localhost:8085/schoolstore/");
 driver.manage().window().setSize(new Dimension(1366, 699));
 driver.findElement(By.linkText("LOGIN")).click();
 driver.findElement(By.id("txtEmail")).sendKeys("admin@admin.com");
 driver.findElement(By.id("txtSenha")).sendKeys("qwer1234");
 driver.findElement(By.cssSelector(".btn")).click();
 {
   WebElement element = driver.findElement(By.id("relatorios"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 Thread.sleep(2000);
 driver.findElement(By.id("relatorios")).click();
 Thread.sleep(5000);
 driver.findElement(By.id("txtDataInicio")).click();
 driver.findElement(By.id("txtDataInicio")).sendKeys("2020-04-09");
 driver.findElement(By.id("txtDataFim")).click();
 driver.findElement(By.id("txtDataFim")).sendKeys("2020-06-11");
 {
   WebElement element = driver.findElement(By.cssSelector(".btn"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 driver.findElement(By.cssSelector(".btn")).click();
 {
   WebElement element = driver.findElement(By.tagName("body"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element, 0, 0).perform();
 }
 Thread.sleep(5000);
 driver.findElement(By.id("txtDataInicio")).click();
 driver.findElement(By.id("txtDataInicio")).sendKeys("");
 driver.findElement(By.cssSelector(".justify-items-center > .col-lg-12")).click();
 {
   WebElement element = driver.findElement(By.cssSelector(".btn"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 driver.findElement(By.cssSelector(".btn")).click();
 {
   WebElement element = driver.findElement(By.tagName("body"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element, 0, 0).perform();
 }
 Thread.sleep(5000);
 driver.findElement(By.id("txtDataInicio")).click();
 driver.findElement(By.id("txtDataInicio")).sendKeys("2020-05-14");
 driver.findElement(By.cssSelector(".justify-items-center > .col-lg-12")).click();
 driver.findElement(By.id("txtDataFim")).sendKeys("");
 driver.findElement(By.cssSelector(".justify-items-center > .col-lg-12")).click();
 {
   WebElement element = driver.findElement(By.cssSelector(".btn"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 driver.findElement(By.cssSelector(".btn")).click();
 {
   WebElement element = driver.findElement(By.tagName("body"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element, 0, 0).perform();
 }
 {
   WebElement element = driver.findElement(By.id("txtDataInicio"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).clickAndHold().perform();
 }
 {
   WebElement element = driver.findElement(By.cssSelector(".col-lg-6:nth-child(1)"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).release().perform();
 }
 Thread.sleep(5000);
 driver.findElement(By.id("txtDataInicio")).sendKeys("\"\"");
 driver.findElement(By.cssSelector(".justify-items-center > .col-lg-12")).click();
 {
   WebElement element = driver.findElement(By.cssSelector(".btn"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 driver.findElement(By.cssSelector(".btn")).click();
 {
   WebElement element = driver.findElement(By.tagName("body"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element, 0, 0).perform();
 }
 Thread.sleep(5000);
}
}